return {
  mode_fg               = '#000000',
  main                  = '#ff87ff',
  normal                = '#d39ea5',
  pending               = '#909481',
  insert                = '#7f8d7b',
  command               = '#cdb97d',
  visual                = '#7d90a5',
  visuall               = '#cb9c7a',
  visualb               = '#755953',
  select                = '#7d90a5',
  replace               = '#ff5757',
  terminal              = '#c678dd',
  shell                 = '#990000',
  path_active_bg        = '#f0efea',
  path_active_fg        = '#000000',
  path_inactive_bg      = '#707278',
  path_inactive_fg      = '#000000',
  path_active_changed   = '#f4606c',
  path_inactive_changed = '#ecad9e',
  pos_bg                = '#474446',
  pos_fg                = '#ffffff',
  info_bg               = '#7A5F6B',
  info_fg               = '#ffffff',
}
